### ISSUE TITLE
Protocol buffers error

### ISSUE THREAD

**Issue by ilkkao** [philippelt/microk8s_prune#3]
Nice tool, just what I needed for my older microk8s installation

Initially I got error

```
$ pip install containerd
$ ./microk8s_prune.py
Traceback (most recent call last):
  File "/home/ubuntu/./microk8s_prune.py", line 7, in <module>
    from containerd.services.containers.v1 import containers_pb2_grpc, containers_pb2
  File "/home/ubuntu/.local/lib/python3.10/site-packages/containerd/services/containers/v1/containers_pb2_grpc.py", line 5, in <module>
    from containerd.services.containers.v1 import containers_pb2 as containerd_dot_services_dot_containers_dot_v1_dot_containers__pb2
  File "/home/ubuntu/.local/lib/python3.10/site-packages/containerd/services/containers/v1/containers_pb2.py", line 14, in <module>
    from containerd.vendor.gogoproto import gogo_pb2 as containerd_dot_vendor_dot_gogoproto_dot_gogo__pb2
  File "/home/ubuntu/.local/lib/python3.10/site-packages/containerd/vendor/gogoproto/gogo_pb2.py", line 29, in <module>
    goproto_enum_prefix = _descriptor.FieldDescriptor(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/google/protobuf/descriptor.py", line 560, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
```

`pip install protobuf==3.20.*` solved it. I don't know python really but maybe the script can be updated instead?

**Comment by philippelt** [comment]
Hello, thanks for reporting the problem.

Unfortunately, the problem is in many packages that use protobuf. It seems that V4 of protobuf introduces a breaking change and that interfaces built with previous versions no longer works.

You can check that easily:
```
$ python3
>>>  from containerd.services.containers.v1 import containers_pb2 as containerd_dot_services_dot_containers_dot_v1_dot_containers__pb2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/containerd/services/containers/v1/containers_pb2.py", line 14, in <module>
    from containerd.vendor.gogoproto import gogo_pb2 as containerd_dot_vendor_dot_gogoproto_dot_gogo__pb2
  File "/usr/local/lib/python3.10/dist-packages/containerd/vendor/gogoproto/gogo_pb2.py", line 29, in <module>
    goproto_enum_prefix = _descriptor.FieldDescriptor(
  File "/usr/local/lib/python3.10/dist-packages/google/protobuf/descriptor.py", line 560, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
```
Short-term consequence : there is no other work-around than returning to 3.20 !

**Comment by ilkkao** [comment]
right, maybe document the workaround in readme. I found it by googling the error message. Feel free to close also if this is obvious.

**Comment by ycadin** [comment]
I think you can solve the problem with right requirements:

$ cat requirements.txt
protobuf >= 3.13.0, <= 3.20.*
containerd

$ pip3 install -r requirements.txt

It works for me.

**Comment by philippelt** [comment]
Done

Many thanks for the suggestion. It may save some time to users.
